export const FETCH_EVENTS_BEGIN = "FETCH_EVENTS_BEGIN";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";

export const SET_CENTER = "SET_CENTER";
export const SET_CLUSTERS = "SET_CLUSTERS";
export const SET_FILTERED_EVENTS = "SET_FILTERED_EVENTS";
export const SET_EVENTS = "SET_EVENTS";
export const SET_ZOOM = "SET_ZOOM";
export const SET_DRAWER = "SET_DRAWER";